### ISSUE TITLE
not able to register service workers

### ISSUE THREAD

**Issue by annezhou920** [ragingwind/next-workbox#3]
When I follow the instructions to register `ServiceWorker`, Chrome is unable to detect a service worker. Where is `/sw.js` coming from?

```
import ServiceWorker from 'next-workbox/service-worker'

<ServiceWorker
              src={'/sw.js'}
              scope={'/'}
              unregister={process.env.NODE_ENV !== 'production'}
          />

**Comment by unrealhero18** [comment]
Your src value should be `/static/workbox/sw.js`

The Service Workers assets are generated during build
